// <auto-generated />
using System;
using Askii.backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119030034_InitialRefactor")]
    partial class InitialRefactor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Askii.backend.Model.Answer", b =>
                {
                    b.Property<string>("AnswerID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponderUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("AnswerID");

                    b.HasIndex("QuestionID")
                        .IsUnique();

                    b.HasIndex("ResponderUID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Askii.backend.Model.Question", b =>
                {
                    b.Property<string>("QuestionID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AskerUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("QuestionID");

                    b.HasIndex("AskerUID");

                    b.HasIndex("SessionID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Askii.backend.Model.Session", b =>
                {
                    b.Property<string>("SessionID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionAdminUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionTopic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SessionID");

                    b.HasIndex("SessionAdminUID");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Askii.backend.Model.User", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Askii.backend.Model.UserSession", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.Property<string>("SessionID")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UID", "SessionID");

                    b.HasIndex("SessionID");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("QuestionVote", b =>
                {
                    b.Property<string>("VoteID")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoteType")
                        .HasColumnType("INTEGER");

                    b.HasKey("VoteID");

                    b.HasIndex("QuestionID");

                    b.HasIndex("UserID", "QuestionID")
                        .IsUnique();

                    b.ToTable("QuestionVotes");
                });

            modelBuilder.Entity("Askii.backend.Model.Answer", b =>
                {
                    b.HasOne("Askii.backend.Model.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("Askii.backend.Model.Answer", "QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Askii.backend.Model.User", "Responder")
                        .WithMany()
                        .HasForeignKey("ResponderUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Responder");
                });

            modelBuilder.Entity("Askii.backend.Model.Question", b =>
                {
                    b.HasOne("Askii.backend.Model.User", "Asker")
                        .WithMany()
                        .HasForeignKey("AskerUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Askii.backend.Model.Session", "Session")
                        .WithMany("Questions")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asker");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Askii.backend.Model.Session", b =>
                {
                    b.HasOne("Askii.backend.Model.User", "SessionAdmin")
                        .WithMany()
                        .HasForeignKey("SessionAdminUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionAdmin");
                });

            modelBuilder.Entity("Askii.backend.Model.UserSession", b =>
                {
                    b.HasOne("Askii.backend.Model.Session", "Session")
                        .WithMany("SessionParticipants")
                        .HasForeignKey("SessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Askii.backend.Model.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuestionVote", b =>
                {
                    b.HasOne("Askii.backend.Model.Question", "Question")
                        .WithMany("Votes")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Askii.backend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Askii.backend.Model.Question", b =>
                {
                    b.Navigation("Answer")
                        .IsRequired();

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Askii.backend.Model.Session", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("SessionParticipants");
                });

            modelBuilder.Entity("Askii.backend.Model.User", b =>
                {
                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
